name: Build (Linux)

on:
  push:
    paths:
      - 'source/source.cpp'
      - 'CMakeLists.txt'
      - '.github/workflows/linux.yml'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Setup GCC and Ninja
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-11 ninja-build
        echo "CC=gcc-11" >> $GITHUB_ENV
        echo "CXX=g++-11" >> $GITHUB_ENV

    - name: Download VapourSynth headers
      run: |
        wget -q -O vs.zip https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth*/ vapoursynth

    - name: Configure
      run: cmake -S . -B build -G Ninja
        -D VS_INCLUDE_DIR="`pwd`/vapoursynth/include"
        -D CMAKE_BUILD_TYPE=Release
        -D CMAKE_CXX_FLAGS_RELEASE="-ffast-math -march=x86-64-v3 -Wall"

    - name: Build
      run: cmake --build build --config Release --verbose

    - name: Install
      run: cmake --install build --prefix artifact

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: VapourSynth-BoxBlur-Linux
        path: artifact

